# Generated by Django 5.1.6 on 2025-04-19 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('general_medicine', 'General Medicine'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('radiology', 'Radiology'), ('surgery', 'Surgery'), ('other', 'Other')], max_length=100)),
                ('appointment_type', models.JSONField(blank=True, default=list, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('experience_years', models.IntegerField()),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('board_certified', models.BooleanField(default=False)),
                ('languages_spoken', models.JSONField(blank=True, null=True)),
                ('star_rating', models.FloatField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(null=True)),
                ('available_days', models.JSONField(blank=True, null=True)),
                ('available_time_slots', models.JSONField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accepts_new_patients', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='account.profile')),
            ],
        ),
    ]
