# Generated by Django 5.1.6 on 2025-04-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctorprofile_appointment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='consultation_fee',
            new_name='fees',
        ),
    ]
