# Generated by Django 5.1.6 on 2025-04-19 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_consultation_fee_doctorprofile_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
