# Generated by Django 5.1.6 on 2025-04-19 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_appointmentslot_created_at_appointmentslot_is_booked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='time_span',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='to_time',
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='appointment_type',
            field=models.CharField(choices=[('general_consultation', 'General Consultation'), ('follow_up_visit', 'Follow-up Visit'), ('online_consultation', 'Online Consultation'), ('offline_consultation', 'Offline Consultation')], max_length=32),
        ),
        migrations.CreateModel(
            name='Appointment_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('appointment_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_times', to='doctor.appointmentslot')),
            ],
        ),
    ]
