# Generated by Django 5.1.6 on 2025-04-19 13:38

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_appointmentslot_from_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='appointment_type',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='appointment_time',
            name='appointment_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('general_consultation', 'General Consultation'), ('follow_up_visit', 'Follow-up Visit'), ('online_consultation', 'Online Consultation'), ('offline_consultation', 'Offline Consultation')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment_time',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
