# Generated by Django 5.1.6 on 2025-04-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_remove_appointmentslot_appointment_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentSlot',
            new_name='AppointmentDateSlot',
        ),
        migrations.RenameModel(
            old_name='Appointment_Time',
            new_name='AppointmentTimeSlot',
        ),
    ]
