# Generated by Django 5.1.6 on 2025-04-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_rename_appointmentslot_appointmentdateslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttimeslot',
            name='duration',
            field=models.CharField(choices=[('15', '15 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], default='60', max_length=3),
        ),
    ]
