# Generated by Django 5.1.6 on 2025-04-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_appointmenttimeslot_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmenttimeslot',
            old_name='appointment_slot',
            new_name='appointment_date_slot',
        ),
    ]
