# Generated by Django 5.2.1 on 2025-05-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_rename_appointment_slot_appointmenttimeslot_appointment_date_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmenttimeslot',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='appointmenttimeslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('unavailable', 'Unavailable'), ('break', 'Break')], default='unavailable', max_length=20),
        ),
    ]
