# Generated by Django 5.2.1 on 2025-05-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_remove_appointmenttimeslot_is_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttimeslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('unavailable', 'Unavailable'), ('break', 'Break')], default='available', max_length=20),
        ),
    ]
