# Generated by Django 5.2.1 on 2025-05-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_alter_appointmenttimeslot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttimeslot',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
