# Generated by Django 5.2.1 on 2025-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_appointmenttimeslot_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='star_rating',
            field=models.FloatField(blank=True, default=3, null=True),
        ),
    ]
