# Generated by Django 5.2.1 on 2025-05-13 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_activitylog_options_activitylog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='account.profile'),
        ),
    ]
