# Generated by Django 5.2.1 on 2025-05-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_age_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
