# Generated by Django 5.2.1 on 2025-06-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('requested', 'Requested'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='requested', max_length=10),
        ),
    ]
