# Generated by Django 5.2.1 on 2025-06-15 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_conversation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('call_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='video', max_length=5)),
                ('connection_status', models.CharField(choices=[('connected', 'Connected'), ('requested', 'Requested'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('reconnecting', 'Reconnecting')], default='requested', max_length=20)),
                ('participants', models.ManyToManyField(related_name='calls', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to='account.profile')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='account.callconnection')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to='account.profile')),
            ],
        ),
    ]
