# Generated by Django 5.2.1 on 2025-06-17 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_conversation_conv_type'),
        ('doctor', '0012_appointmenttimeslot_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_d_slots', to='doctor.appointmentdateslot'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
