# Generated by Django 5.2.1 on 2025-06-17 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_conversation_appointment_alter_conversation_uuid'),
        ('doctor', '0012_appointmenttimeslot_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='appointment',
        ),
        migrations.AddField(
            model_name='calls',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_d_slots', to='doctor.appointmentdateslot'),
        ),
    ]
