# Generated by Django 5.2.1 on 2025-06-17 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_conversation_appointment_calls_appointment'),
        ('patient', '0020_appointment_confirm_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patient.appointment'),
        ),
    ]
