# Generated by Django 5.2.1 on 2025-06-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_calls_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='ongoing', max_length=10),
        ),
    ]
