# Generated by Django 5.2.1 on 2025-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_calls_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calls',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='calls',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='calls',
            name='last_req',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('active', 'Active'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=10),
        ),
    ]
