# Generated by Django 5.2.1 on 2025-06-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_calls_duration_remove_calls_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='last_req',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
