# Generated by Django 5.2.1 on 2025-06-28 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_profile_role_review'),
        ('doctor', '0013_alter_doctorprofile_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviews', to='doctor.doctorprofile'),
        ),
    ]
