# Generated by Django 5.2.1 on 2025-06-28 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_review_doctor'),
        ('patient', '0024_alter_prescription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_Calls', to='patient.appointment'),
        ),
    ]
