# Generated by Django 5.2.1 on 2025-06-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_calls_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reset_password_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
