# Generated by Django 5.2.1 on 2025-06-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_profile_reset_password_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reset_password_token',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='reset_password_token_expiry',
            new_name='token_expiry',
        ),
    ]
