# Generated by Django 5.2.1 on 2025-06-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_message_is_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='conv_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_call',
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('call', 'Call'), ('appoinment', 'Appoinment')], default='call', max_length=20),
        ),
    ]
