# Generated by Django 5.2.1 on 2025-06-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_conversation_conv_type_remove_message_is_call_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('call', 'Call'), ('appoinment', 'Appoinment'), ('text', 'Text')], default='text', max_length=20),
        ),
    ]
