# Generated by Django 5.2.1 on 2025-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='lab_report_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calls',
            name='prescription_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calls',
            name='quick_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('call', 'Call'), ('appoinment', 'Appoinment'), ('text', 'Text'), ('started', 'Started')], default='text', max_length=20),
        ),
    ]
