# Generated by Django 5.1.6 on 2025-04-19 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_profile_pic'),
        ('doctor', '0009_rename_appointment_slot_appointmenttimeslot_appointment_date_slot'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmenttype', models.CharField(choices=[('general_consultation', 'General Consultation'), ('follow_up_visit', 'Follow-up Visit'), ('online_consultation', 'Online Consultation'), ('offline_consultation', 'Offline Consultation')], default='general_consultation', max_length=50)),
                ('appointment_date', models.DateTimeField()),
                ('appointment_time', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(blank=True, upload_to='appointment_files/')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_appointments', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_appointments', to='account.profile')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_appointments', to='doctor.appointmenttimeslot')),
            ],
        ),
    ]
