# Generated by Django 5.1.6 on 2025-04-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='appointment_date_str',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='appointment_time_str',
        ),
    ]
