# Generated by Django 5.1.6 on 2025-04-19 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_rename_appointment_slot_appointmenttimeslot_appointment_date_slot'),
        ('patient', '0003_rename_appointment_date_appointment_appointment_date_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_appointments', to='doctor.doctorprofile'),
        ),
    ]
