# Generated by Django 5.1.6 on 2025-04-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_appointment_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmenttype',
            new_name='appointment_type',
        ),
    ]
