# Generated by Django 5.1.6 on 2025-04-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_rename_appointmenttype_appointment_appointment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date_str',
            new_name='appointment_date',
        ),
    ]
