# Generated by Django 5.1.6 on 2025-04-21 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_profile_pic'),
        ('doctor', '0009_rename_appointment_slot_appointmenttimeslot_appointment_date_slot'),
        ('patient', '0011_appointment_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_dosage', models.CharField(blank=True, max_length=50)),
                ('default_frequency', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True, help_text="E.g. 'Take with food…'")),
                ('side_effects', models.TextField(blank=True, help_text="E.g. 'May cause dizziness…'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_dosage', models.CharField(help_text='e.g. "10mg", "500mg".', max_length=50)),
                ('update_frequency', models.CharField(help_text='Descriptive frequency, e.g. "Once daily", "Three times daily".', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions for the medication.')),
                ('status', models.CharField(choices=[('active', 'Running'), ('completed', 'Completed'), ('discontinued', 'Discontinued'), ('break', 'In Break')], default='active', help_text='Current status of the medication.', max_length=50)),
                ('start_date', models.DateField(help_text='When the patient should start this medication.')),
                ('end_date', models.DateField(help_text='When the course ends or next review is due.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patient.medicine')),
                ('prescribing_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.doctorprofile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeschedule', to='patient.prescription')),
            ],
            options={
                'ordering': ['time'],
                'unique_together': {('prescription', 'time')},
            },
        ),
    ]
