# Generated by Django 5.1.6 on 2025-04-22 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_profile_pic'),
        ('patient', '0012_medicine_prescription_prescriptionschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to='account.profile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
