# Generated by Django 5.2.1 on 2025-05-12 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_profile_pic'),
        ('doctor', '0009_rename_appointment_slot_appointmenttimeslot_appointment_date_slot'),
        ('patient', '0013_appointment_cancel_reason_appointment_cancled_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('pending', 'Pending'), ('neutral', 'Neutral')], max_length=10)),
                ('report_description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports_doctor', to='doctor.doctorprofile')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports_profile', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LabReportParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=50)),
                ('reference_range', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('normal', 'Normal')], max_length=10)),
                ('lab_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='patient.labreport')),
            ],
        ),
    ]
