# Generated by Django 5.2.1 on 2025-05-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_labreport_labreportparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionschedule',
            name='had_taken',
            field=models.BooleanField(default=False),
        ),
    ]
