# Generated by Django 5.2.1 on 2025-05-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_prescriptionschedule_had_taken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prescriptionschedule',
            unique_together=set(),
        ),
    ]
