# Generated by Django 5.2.1 on 2025-05-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_alter_prescriptionschedule_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prescriptionschedule',
            unique_together={('prescription', 'time')},
        ),
    ]
