# Generated by Django 5.2.1 on 2025-05-13 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_alter_prescriptionschedule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
