# Generated by Django 5.2.1 on 2025-05-18 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_profile_age'),
        ('patient', '0019_alter_appointment_profile_alter_labreport_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirm_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_appointments', to='account.profile'),
        ),
    ]
