# Generated by Django 5.2.1 on 2025-06-21 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_doctorprofile_star_rating'),
        ('patient', '0020_appointment_confirm_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors_appointments', to='doctor.doctorprofile'),
        ),
    ]
