# Generated by Django 5.2.1 on 2025-06-27 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_labreport_created_at_labreport_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
