# Generated by Django 5.2.1 on 2025-06-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0023_alter_prescription_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued'), ('break', 'In Break')], default='active', help_text='Current status of the medication.', max_length=50),
        ),
    ]
